'use strict';

var USER_SET_FACEBOOK_TOKEN = require('./USER_SET_FACEBOOK_TOKEN');
var USER_NETWORK_VERIFICATION_SEND = require('./USER_NETWORK_VERIFICATION_SEND');
var USER_NETWORK_VERIFICATION_VERIFY = require('./USER_NETWORK_VERIFICATION_VERIFY');

module.exports = {
	USER_SET_FACEBOOK_TOKEN: USER_SET_FACEBOOK_TOKEN,
	USER_NETWORK_VERIFICATION_SEND: USER_NETWORK_VERIFICATION_SEND,
	USER_NETWORK_VERIFICATION_VERIFY: USER_NETWORK_VERIFICATION_VERIFY
};