const USER_SET_FACEBOOK_TOKEN = require('./USER_SET_FACEBOOK_TOKEN');
const USER_NETWORK_VERIFICATION_SEND = require('./USER_NETWORK_VERIFICATION_SEND');
const USER_NETWORK_VERIFICATION_VERIFY = require('./USER_NETWORK_VERIFICATION_VERIFY');

module.exports = {
	USER_SET_FACEBOOK_TOKEN,
	USER_NETWORK_VERIFICATION_SEND,
	USER_NETWORK_VERIFICATION_VERIFY
};