export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const LOAD_USER_SUCCESS = 'LOAD_TASKS_SUCCESS';
export const UNLOAD_USER_SUCCESS = 'UNLOAD_TASKS_SUCCESS';
